runtime: nodejs20
service: default  # Remove if you want "default" service
env_variables:
  DATABASE_URL: "file:./server/tmp/prod.db"
  NODE_ENV: production

handlers:
  # Serve all traffic via Express
  - url: /.*
    script: auto