name: Deploy to Google App Engine

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_ENV: production
  DATABASE_URL: ${{ secrets.CONNECTION_STRING }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install all dependencies
        run: npm ci --include=dev

      - name: Build Vite frontend
        run: npm run build
        
      - name: Render app.yaml with secrets
        run: |
          cat > app.yaml <<EOF
          env_variables:
            DATABASE_URL: "${{ secrets.CONNECTION_STRING }}"
          EOF

      - name: Prepare production files
        run: |
          mkdir -p server/public
          cp -R dist/* server/public/
          npx prisma generate
          npx prisma migrate deploy

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Google App Engine
        run: |
          gcloud config set app/cloud_build_timeout 1600
          gcloud app deploy app.yaml --quiet --verbosity=debug

